language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "uklimaschewski"
    token: $SONAR_TOKEN

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Dsonar.projectKey=uklimaschewski_EvalEx -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
